# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: waggle

builds:
  - main: ./cmd/waggle/
    binary: waggle
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    exclude:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: exedev
    name: queen-bee
  draft: false
  prerelease: auto
