# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: waggle

builds:
  - main: ./cmd/waggle/
    binary: waggle
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: HexSleeves
    name: waggle
  draft: false
  prerelease: auto
